### ISSUE TITLE
ISO-20 AuthorizationSetupRes AuthorizationServices

### ISSUE THREAD

**Issue by SebaLukas** [EVerest/cbexigen#17]
Hi :)

the `AuthorizationServices` in the `AuthorizationSetupRes` has the following definition:

`<xs:element name="AuthorizationServices" type="authorizationType" maxOccurs="2"/>.`

So the element `AuthorizationServices` consists of an array with the `authorizationType ` and can contain one or two values.

In the encode and decode function of the `AuthorizationSetupRes` message always two elements are assumed. I think this should not be the case.

Also, the `CertificateInstallationService` element of the `AuthorizationSetupRes` message is decoded and encoded twice. Which can't be right either.

Many Greetings
Sebastian

**Comment by barsnick** [comment]
Regarding `AuthorizationServices`:
Interestingly, ISO 15118-2 has no arrays of elements which are _not_ at the end of sequences. So the error in creation of the according grammar only appeared with ISO 15118-20. (All other such occurrences in ISO 15118-20 seem to be in the WPT schema, which should therefore also be affected.)

The duplicate `CertificateInstallationService` is an aftereffect of the above phenomenon.

We will take a look at the grammar generation.
