### ISSUE TITLE
Encode/Decode "xmldsig" messages

### ISSUE THREAD

**Issue by coollhc77** [EVerest/cbexigen#42]
Hello.
Are there any plans to add the ability to generate code that can encode/decode "xmldsig" messages?
I think I will need it when testing the "PNC" feature.

**Comment by barsnick** [comment]
The messages and the PnC relevant fields are currently coded within the protocols' code (i.e. as part of the `iso2`/`iso20` code paths), and not separately in an XMLDsig namespace. All messages and header components can already be encoded and decoded successfully.

If you are looking for additional functions to create the fragments (e.g. for calculating their hashes, for verification of signatures): This feature set is currently under development and will be added shortly.

Is this what you're looking for?

**Comment by coollhc77** [comment]
Hi @barsnick
Yes, that's right.
This question is about digital signatures, such as the one below.

(ns=http://www.w3.org/2000/09/xmldsig#): {"SignedInfo": {"CanonicalizationMethod": {"Algorithm": "http://www.w3.org/TR/canonical-exi/"}, "SignatureMethod": {"Algorithm": "http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"}, "Reference": [{"Transforms": {"Transform": [{"Algorithm": "http://www.w3.org/TR/canonical-exi/"}]}, "DigestMethod": {"Algorithm": "http://www.w3.org/2001/04/xmlenc#sha256"}, "DigestValue": "do+VpqJm0RSIxtLvRtJvovke+tnpEVaXnsuxJ1tLGrQ=", "URI": "#id1"}]}}

EXI-encoded message: 808112b43a3a381d1797bbbbbb973b999737b93397aa2917b1b0b737b734b1b0b616b2bc3497a1ab43a3a381d1797bbbbbb973b999737b933979918181897981a17bc36b63239b4b396b6b7b93291b2b1b239b096b9b430991a9b220623696431025687474703a2f2f7777772e77332e6f72672f54522f63616e6f6e6963616c2d6578692f4852d0e8e8e0745e5eeeeeee5cee665cdee4ce5e646060625e60685ef0dad8cadcc646e6d0c2646a6c840ed1f2b4d44cda229118da5de8da4df45f23df5b3d222ad2f3d97624eb6963568370

**Comment by barsnick** [comment]
Hi, @coollhc77,
we have implemented such fragment coders in the most recent code (from https://github.com/EVerest/cbexigen/commit/d7d44b415aecf834e17dded340ab7f6075c60ee9). Please check the latest generated code.

**Comment by barsnick** [comment]
Closing as fixed with https://github.com/EVerest/cbexigen/pull/43.
