### ISSUE TITLE
Why C and not C++ ?

### ISSUE THREAD

**Issue by andreichalapco** [EVerest/cbexigen#77]
### Describe the problem

It occured to me when looking at the generated code: 

```c
void init_iso2_ServiceDetailReqType(struct iso2_ServiceDetailReqType* ServiceDetailReqType) {
    (void) ServiceDetailReqType; // this does nothing, no variable is initialized -> probably just for compiler warning
}
```

or
```c
void init_iso2_MessageHeaderType(struct iso2_MessageHeaderType* MessageHeaderType) {
    MessageHeaderType->Notification_isUsed = 0u; // default initialization
    MessageHeaderType->Signature_isUsed = 0u;
}
``` 

that we basically could do this a lot better in c++ with objects ... the syntax would be also a lot cleaner. 
For which reason was a c implementation used? maybe I don't see the advantages

**Comment by barsnick** [comment]
> For which reason was a c implementation used?

To be compatible with embedded systems which are constrained in the use of C++. C is the common denominator. (The original authors actually had the code integrated into such a product, so this is not a hypothetical scenario.)

Please feel free to modify and create a PR, best as an additional path / separate templates to be chosen by config, to optionally create proper C++ code. This would be very welcomed, especially for integration into the EVerest modules.

Unfortunately, the low- and mid-level layers of the code generator are not properly separated. Nevertheless, creating C++ code should be possible without too many modifications. (Very little stuff is C-specific.)

The same for other languages. Rust support would certainly also be welcome.

**Comment by andreichalapco** [comment]
Thx for the guidelines and explanation!
