### ISSUE TITLE
Encoded SupportedAppProtocolReq seems corrupt and cannot be decoded

### ISSUE THREAD

**Issue by scotty1269** [EVerest/cbexigen#78]
### Describe the bug

Generated Hex stream from cbexigen cannot be decoded neither with openV2G, nor with EXIficient, nor with cbexigen itself. Worked when encoding with openV2G.

### To Reproduce

SupportedAppProtocolReq:
<?xml version="1.0" encoding="UTF-8"?><ns4:supportedAppProtocolReq xmlns:ns4="urn:iso:15118:2:2010:AppProtocol" xmlns:xsi="[http://www.w3.org/2001/XMLSchema-instance"](http://www.w3.org/2001/XMLSchema-instance%22) xmlns:ns3="[http://www.w3.org/2001/XMLSchema"><AppProtocol><ProtocolNamespace>urn:din:70121:2012:MsgDef</ProtocolNamespace><VersionNumberMajor>2</VersionNumberMajor><VersionNumberMinor>0</VersionNumberMinor><SchemaID>3</SchemaID><Priority>3</Priority></AppProtocol><AppProtocol><ProtocolNamespace>urn:iso:15118:2:2013:MsgDef</ProtocolNamespace><VersionNumberMajor>2</VersionNumberMajor><VersionNumberMinor>0</VersionNumberMinor><SchemaID>2</SchemaID><Priority>2</Priority></AppProtocol><AppProtocol><ProtocolNamespace>urn:iso:std:iso:15118:-20:DC</ProtocolNamespace><VersionNumberMajor>1</VersionNumberMajor><VersionNumberMinor>0</VersionNumberMinor><SchemaID>1</SchemaID><Priority>2</Priority></AppProtocol></ns4:supportedAppProtocolReq>](http://www.w3.org/2001/XMLSchema%22%3E%3CAppProtocol%3E%3CProtocolNamespace%3Eurn:din:70121:2012:MsgDef%3C/ProtocolNamespace%3E%3CVersionNumberMajor%3E2%3C/VersionNumberMajor%3E%3CVersionNumberMinor%3E0%3C/VersionNumberMinor%3E%3CSchemaID%3E3%3C/SchemaID%3E%3CPriority%3E3%3C/Priority%3E%3C/AppProtocol%3E%3CAppProtocol%3E%3CProtocolNamespace%3Eurn:iso:15118:2:2013:MsgDef%3C/ProtocolNamespace%3E%3CVersionNumberMajor%3E2%3C/VersionNumberMajor%3E%3CVersionNumberMinor%3E0%3C/VersionNumberMinor%3E%3CSchemaID%3E2%3C/SchemaID%3E%3CPriority%3E2%3C/Priority%3E%3C/AppProtocol%3E%3CAppProtocol%3E%3CProtocolNamespace%3Eurn:iso:std:iso:15118:-20:DC%3C/ProtocolNamespace%3E%3CVersionNumberMajor%3E1%3C/VersionNumberMajor%3E%3CVersionNumberMinor%3E0%3C/VersionNumberMinor%3E%3CSchemaID%3E1%3C/SchemaID%3E%3CPriority%3E2%3C/Priority%3E%3C/AppProtocol%3E%3C/ns4:supportedAppProtocolReq%3E)
 
Hex stream generated from cbexigen:
8000f3ab9371d34b9b79d39ba321d34b9b79d189a98989c1d1699181d22218010000040001d75726e3a69736f3a31353131383a323a323031333a4d736744656600400001008036eae4dc74c8d2dc746e606264627464606264749ae6ce88cacc008000030
 
Hex stream generated from openv2g:
8000dbab9371d3234b71d1b981899189d191818991d26b9b3a232b300200000c0801d75726e3a69736f3a31353131383a323a323031333a4d73674465660040000100803ceae4dc74d2e6de74e6e8c874d2e6de74626a626270745a646074888600400001011

**Comment by chausGit** [comment]
I have successfully decoded the hex sream from openv2g with cbv2g.

`{"AppProtocol":[
    {"ProtocolNamespace":"urn:din:70121:2012:MsgDef","VersionNumberMajor":2,"VersionNumberMinor":0,"SchemaID":3,"Priority":3},
    {"ProtocolNamespace":"urn:iso:15118:2:2013:MsgDef","VersionNumberMajor":2,"VersionNumberMinor":0,"SchemaID":2,"Priority":2},
    "{"ProtocolNamespace":"urn:iso:std:iso:15118:-20:DC","VersionNumberMajor":1,"VersionNumberMinor":0,"SchemaID":1,"Priority":2}]};`

I have also successfully encoded this JSON string again with cbv2g. 

`Generated: 8000DBAB9371D3234B71D1B981899189D191818991D26B9B3A232B300200000C0801D75726E3A69736F3A31353131383A323A323031333A4D73674465660040000100803CEAE4DC74D2E6DE74E6E8C874D2E6DE74626A626270745A646074888600400001011"`

The result is identical to that of openv2g.
You should check your input in the cbv2g encoder again.
Feel free to share your code here 😊

**Comment by scotty1269** [comment]
C:\Users\karl-heinz.sadler\Downloads
[supportedAppProtocol_code.cpp.txt](https://github.com/EVerest/cbexigen/files/14719657/supportedAppProtocol_code.cpp.txt)
Thanks for the fast response! Attached my code.

**Comment by barsnick** [comment]
Thanks for the code. First an observation:

> Hex stream generated from cbexigen: 8000f3ab9371d34b9b79d39ba321d34b9b79d189a98989c1d1699181d22218010000040001d75726e3a69736f3a31353131383a323a323031333a4d736744656600400001008036eae4dc74c8d2dc746e606264627464606264749ae6ce88cacc008000030
> 
> Hex stream generated from openv2g: 8000dbab9371d3234b71d1b981899189d191818991d26b9b3a232b300200000c0801d75726e3a69736f3a31353131383a323a323031333a4d73674465660040000100803ceae4dc74d2e6de74e6e8c874d2e6de74626a626270745a646074888600400001011

You are apparently encoding two different messages, with a different order of protocols, therefore two different results. (cbV2G: -20, -2, DIN; OpenV2G: DIN, -2, -20).

The hex stream you posted from cbV2G/cbExiGen is largely correct, but you are missing the final byte. Here is the correct stream, which should decode correctly:

8000f3ab9371d34b9b79d39ba321d34b9b79d189a98989c1d1699181d22218010000040001d75726e3a69736f3a31353131383a323a323031333a4d736744656600400001008036eae4dc74c8d2dc746e606264627464606264749ae6ce88cacc008000030**21**

You need to take care that cbV2G counts bytes differently than OpenV2G. Instead of calculating the length of the payload with `exi_bitstream->byte_pos - V2GTP_HEADER_LENGTH`, you should use the function `exi_bitstream_get_length()`. (Background: There may be extra bits which are not taken into account in `byte_pos`.)

Further observations regarding your code:
```
    exi_bitstream_init(exi_bitstream, data, nbytes, 0, nullptr);
    exi_bitstream->byte_pos = V2GTP_HEADER_LENGTH;
```

You could initialize this directly:
```
    exi_bitstream_init(exi_bitstream, data, nbytes, V2GTP_HEADER_LENGTH, nullptr);
```

Furthermore:
```
    memcpy(exidoc->supportedAppProtocolReq.AppProtocol.array[idx].ProtocolNamespace.characters, iso_20_scheme.c_str() , iso_20_scheme.size());
```
While it works in this particular case, you need to be careful that the size given in the third argument does not exceed the size of the target memory area. (Use something like `std::min()`.)

Let us know if this works for you.

**Comment by barsnick** [comment]
By the way, you could have observed in the decoder that it returns an error `EXI_ERROR__BITSTREAM_OVERFLOW`, which means that the decoder is trying to read more data than it was given. This could have hinted at a "good", but short stream.

**Comment by scotty1269** [comment]
Thank you again for your quick feedback! I adapted now the length and now encoding is working fine!
I get following Hex stream: 
8000f3ab9371d34b9b79d39ba321d34b9b79d189a98989c1d1699181d22218010000040001d75726e3a69736f3a31353131383a323a323031333a4d736744656600400001008036eae4dc74c8d2dc746e606264627464606264749ae6ce88cacc00800003021

But when decoding that message I still get an error, I receive Response code "EXI_ERROR__STRINGVALUES_NOT_SUPPORTED".

My encodig code is the sae as above https://github.com/EVerest/cbexigen/files/14719657/supportedAppProtocol_code.cpp.txt

**Comment by barsnick** [comment]
Decodes perfectly here. Please fix your code:

- You should not V2GTP20_ReadHeader() or subtract V2GTP_HEADER_LENGTH, you never added such a header.
- You are passing a std::string, probably the hexadecimal string representation quoted above ("8000f3ab..."). You need to convert that back to binary.

If we change that, even your code snippet works.

**Comment by scotty1269** [comment]
Many thanks for your support! It turned out that a parameter was not correctly initialized. Now also decoding works fine. Please close this issue.
