### ISSUE TITLE
SAP EXI Messages + Code Coverage

### ISSUE THREAD

**Issue by brandonprry** [EVerest/cbexigen#95]
### Describe the problem

Attached is ZIP file with EXI messages and a code coverage report specifically for SAP messages.

![image](https://github.com/user-attachments/assets/a8d605bd-7e2a-45bc-9900-05935d9c7e93)

[sap.zip](https://github.com/user-attachments/files/18049235/sap.zip)

### Describe your solution

Just information.

### Additional context

In the future, hopefully I can provide Main, AC, and DC messages too.

**Comment by SebaLukas** [comment]
Hi :) I don't quite understand your posts. Why did you upload ISO15118-20 Exi messages here? For reference EXI streams for unit tests?
Also, the code coverage reports probably belong to libiso15118 and not cbexigen? Therefore, I think the reports are out of place here. Btw: It is now possible to create a code coverage report for libiso15118.

**Comment by brandonprry** [comment]
These are reference EXI streams for unit tests.

**Comment by brandonprry** [comment]
I saw this in the readme and wanted to provide my EXI streams I use for testing.

![image](https://github.com/user-attachments/assets/f9fe329f-3fde-4b31-9961-24ba4dee27d5)

**Comment by SebaLukas** [comment]
What kind of Exi Streams are these? From real EVs or self-generated?

**Comment by SebaLukas** [comment]
And why is the code coverage included?

**Comment by barsnick** [comment]
> I saw this in the readme and wanted to provide my EXI streams I use for testing.

Okay, this is great. At first glance, I didn't get the format of the files. Is the expected, correct content of the encoded messages also noted somewhere? Which files are the EXI streams? I don't get the layout of your files.

**Comment by brandonprry** [comment]
Sorry, I could have explained it more.

The min/ directory is a minimized set of EXI streams relative to the codepaths taken in libiso15118. Each min/ testcase has a distinct code path taken within the library.

The code coverage report was only to show these EXI messages exercise significant portions of the libiso15118 codebase.

These files have been generated through fuzzing several ISO-15118 implementations, including libiso15118 and openv2g. They are not real-world in the sense that they came from EVs, but the EXI stream set did find two crashes so far.

https://github.com/EVerest/libiso15118/issues/52 https://github.com/EVerest/libiso15118/issues/53 

I will re-open these on this repo soon.

If these are not useful for you, that's perfectly fine. I only saw the message in the readme and thought my testcases would be useful in the same vein.

**Comment by SebaLukas** [comment]
I have looked at the files from the `sap.zip` and I don't understand them at all. Even with your description from your last post.
It would be great if the Exi streams had a specific file format such as here: https://github.com/EVerest/libcbv2g/issues/4

First file: EXI HEX or base64 stream. e.g.: `809a0211d63f74d2297ac9119400`
2nd file: XML file (matching Exi stream)

```xml
<ns7:V2G_Message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns4="http://www.w3.org/2000/09/xmldsig#" xmlns:ns5="urn:din:70121:2012:MsgBody" xmlns:ns6="urn:din:70121:2012:MsgDataTypes" xmlns:ns7="urn:din:70121:2012:MsgDef" xmlns:ns8="urn:din:70121:2012:MsgHeader">
	<ns7:Header>
		<ns8:SessionID>4758FDD348A5EB24</ns8:SessionID>
	</ns7:Header>
	<ns7:Body>
		<ns5:ServiceDiscoveryReq>
			<ns5:ServiceCategory>EVCharging</ns5:ServiceCategory>
		</ns5:ServiceDiscoveryReq>
	</ns7:Body>
</ns7:V2G_Message>
```
At the moment we can't do anything with the files.
